spring:
  application:
    name: gateway
  config:
#    Dùng optional để gateway vẫn có thể chạy khi config server chưa sẵn sàng trong lúc dev.
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
#      Phase 1 chưa có business service nên routes rỗng.
#      Sau này thêm: user, order, payment
      routes:
        - id: user-service
#          uri: lb://USER-SERVICE
          uri: http://localhost:8091
          predicates:
            - Path=/api/users/**

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: localhost:gateway:8080
  client:
#       Đăng ký gateway vào discovery.
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics