server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventories/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/